### ISSUE TITLE
Add info to the About Section

### ISSUE THREAD

**Issue by code-arman** [shstrophies/SHSTrophies#17]
We spent around a year on this project, and idk about yall, but I literally put my blood, sweat, and tears into this. And im sure people will be curious about how this whole project came about–– especially since we won't be at SHS when ppl use it. So we should give some history about the app as well as credit ourselves for making it

**Comment by shayans66** [comment]
History paragraph:
A long time ago, trophies used to be displayed physically in trophy cases in our lobby. However, because of the sheer talent of our athletic teams, the trophies would pile up such that the trophy cases overfilled and we had to archive the vast majority of trophies. The process of maintaining the archive of trophies was painstaking and arduous. At one point, Mrs. Ybarra injured herself while carrying too many trophies to and fro, sustaining a major injury. 
This was the inciting incident that convinced Mr. Torrens that action needed to be taken. Determined to devise a team of skilled computer programmers and mobile developers, Mr. Torrens surveyed the list of potential recruits. Obviously, this didn't take long because he immediately consulted the greatest club on campus, the Application Development (App Dev) club, for help.
Upon hearing of the arduous challenge opportune for capture, then-president Daniel Bessonov assembled a team of coders to bestow the project upon: then-members Ujjwal Krishnamurthi, Arman Rafati, and Shayan Sarnevesht.
Together, these three masterminds worked on the Android java project, coordinating with Mr. Torrens to assemble pictures of all the trophies, developing a beautiful user interface to display them, and devising a clever query database schema by which trophy data would be retrieved. 
The three developers even recruited other gifted underclassmen computer scientists: namely, Vignav Ramesh and Shreyas Rana.
The project was difficult, yet rewarding. Tedious, yet exciting. Impossible, yet possible.
Even amidst the COVID-19 pandemic, the team triumphed through thick and thin, tirelessly hacking away at the project.
Finally after working for over a year, from about February 2019 to May/June 2020, a major advancement was made.
The trophy app had a working product!
Of course, this is a project that will never end. It will require constant maintenance, visual and structural improvements, and new generations of App Dev members who will assume these upkeep responsibilities.
So it is up to you, kind reader, as to whether this trophy app holds a bright future or dim future. Arman, Ujjwal, and Shayan are in the next chapter of their lives pursuing computer science degrees, and will not always be able to manage the app's upkeep.
Join App Dev club today and continue the trophy app's legacy!

**Comment by kujjwal** [comment]
Bro I like this About Us page, but I think it's a little boastful. I made some small changes here, what do y'all think?

A long time ago, trophies used to be displayed physically in trophy cases in our lobby. However, because of the sheer talent of our athletic teams, the trophies would pile up such that the trophy cases overfilled and we had to archive the vast majority of trophies. The process of maintaining the archive of trophies was painstaking and arduous. At one point, Mrs. Ybarra injured herself while carrying too many trophies to and fro, sustaining a major injury.
This was the inciting incident that convinced Mr. Torrens that action needed to be taken. Determined to devise a team of skilled computer programmers and mobile developers, Mr. Torrens surveyed the list of potential recruits. Obviously, this didn't take long because he immediately consulted the greatest club on campus, the Application Development (App Dev) club, for help.
Upon hearing of the arduous challenge opportune for capture, then-presidents Ujjwal Krishnamurthi, Arman Rafati, and Shayan Sarnevesht developed this very mobile application.
Together, these three developers worked on the Android java project, coordinating with Mr. Torrens to assemble pictures of all the trophies, developing a beautiful user interface to display them, and devising a clever query database schema by which trophy data would be retrieved.
The three developers even recruited other gifted underclassmen computer scientists to follow the path they paved: namely, Vignav Ramesh and Shreyas Rana.
The project was difficult, yet rewarding. Tedious, yet exciting. Impossible, yet possible.
Even amidst the COVID-19 pandemic, the team triumphed through thick and thin, tirelessly hacking away at the project.
Finally after working for over a year, from about February 2019 to May/June 2020, a major advancement was made.
The trophy app had a working product!
Of course, this is a project that will never end. It will require constant maintenance, visual and structural improvements, and new generations of App Dev members who will assume these upkeep responsibilities.
So it is up to you, kind reader, as to whether this trophy app holds a bright future or dim future. Ujjwal, Arman, and Shayan are in the next chapter of their lives pursuing computer science degrees, and will not always be able to manage the app's upkeep.
Join App Dev club today and continue the trophy app's legacy!

**Comment by code-arman** [comment]
Lmfao, all good except the name order change 👀. I think im fine letting u have ur name in front one time but i definitely needa have my name in front one time to. If you finish the consistent image loading by monday, i can consider giving you first place name priority in both of those sentences.
